name: e2e-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: docker-compose build
      - name: Docker Up
        run: docker-compose up -d app
      - name: Check running containers
        run: docker ps -a
      - name: Logs
        run: docker-compose logs app
      - name: E2E Tests
        run: docker-compose run --rm --no-deps --entrypoint=pytest app /tests/e2e -v
